In [1]:
%pip install NumPY

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.4 MB 3.6 MB/s eta 0:00:04
   ----- ---------------------------------- 1.6/12.4 MB 3.1 MB/s eta 0:00:04
   ------- -------------------------------- 2.4/12.4 MB 3.2 MB/s eta 0:00:04
   ---------- ----------------------------- 3.4/12.4 MB 3.8 MB/s eta 0:00:03
   --------------- ------------------------ 4.7/12.4 MB 4.1 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.4 MB 4.5 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.4 MB 4.9 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.4 MB 5.3 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.4 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 5.7 MB/s  0:00:02
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
# Step 1: Import NumPy 
import numpy as np 

# Step 2: Create a 1D array representing years of experience 
years_exp = np.array([1, 3, 5, 7, 10]) 
print("Years of Experience:", years_exp) 

# Step 3: Create a 2D array representing sample salaries (in thousands) 
salaries = np.array([[50, 60, 70], [80, 90, 100]]) 
print("Salary Matrix:\n", salaries) 

# Step 4: Create an array of zeros and ones for placeholder analysis 
zeros_array = np.zeros((2, 2))  # 2x2 zeros 
ones_array = np.ones((2, 3))    # 2x3 ones 
print("Zeros Array:\n", zeros_array) 
print("Ones Array:\n", ones_array)

Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
# Step 1: Import NumPy
import numpy as np

# Step 2: Create a 1D array representing years of experience
years_exp = np.array([1, 3, 5, 7, 10, 12, 15])  # Added 2 more data points
print("Years of Experience:", years_exp)

# Step 3: Create a 2D array representing sample salaries (in thousands)
salaries = np.array([
    [50, 60, 70],
    [80, 90, 100],
    [110, 120, 130],   # Added row
    [140, 150, 160]    # Added row
])
print("Salary Matrix:\n", salaries)

# Step 4: Create an array of zeros and ones for placeholder analysis
zeros_array = np.zeros((2, 2))   # 2x2 zeros
ones_array = np.ones((2, 3))     # 2x3 ones
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

# Step 5: Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

Years of Experience: [ 1  3  5  7 10 12 15]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]
 [110 120 130]
 [140 150 160]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# Step 1: Element-wise addition 
exp_plus_5 = years_exp + 5  # Add 5 years to all experience values 
print("Years + 5:", exp_plus_5) 

# Step 2: Element-wise multiplication 
exp_times_2 = years_exp * 2  # Multiply all values by 2 
print("Years * 2:", exp_times_2) 

# Step 3: Dot product (simulate salary projections) 
sample1 = np.array([1, 2, 3]) 
sample2 = np.array([4, 5, 6]) 
dot_result = np.dot(sample1, sample2) 
print("Dot Product:", dot_result) 

Years + 5: [ 6  8 10 12 15 17 20]
Years * 2: [ 2  6 10 14 20 24 30]
Dot Product: 32


In [6]:
import numpy as np

# Sample array of years of experience
years_exp = np.array([1, 3, 5, 7, 10])

# Step 1: Element-wise addition
exp_plus_5 = years_exp + 5   # Add 5 years to all experience values
print("Years + 5:", exp_plus_5)

# Step 2: Element-wise multiplication
exp_times_2 = years_exp * 2  # Multiply all values by 2
print("Years * 2:", exp_times_2)

# Step 3: Dot product (simulate salary projections)
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)

# Try It: Subtraction
exp_minus_2 = years_exp - 2
print("Years - 2:", exp_minus_2)

# Try It: Division
exp_div_2 = years_exp / 2
print("Years / 2:", exp_div_2)

# Try It: Apply exponential function
exp_values = np.exp(years_exp)
print("exp(years_exp):", exp_values)

# Try It: Apply logarithm (natural log)
log_values = np.log(years_exp)
print("log(years_exp):", log_values)

Years + 5: [ 6  8 10 12 15]
Years * 2: [ 2  6 10 14 20]
Dot Product: 32
Years - 2: [-1  1  3  5  8]
Years / 2: [0.5 1.5 2.5 3.5 5. ]
exp(years_exp): [2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 2.20264658e+04]
log(years_exp): [0.         1.09861229 1.60943791 1.94591015 2.30258509]


In [7]:
# Step 1: Access individual element 
print("First year of experience:", years_exp[0]) 

# Step 2: Slice arrays 
print("First two salaries:", salaries[0, :2])  # First two elements of first row 

# Step 3: Access all rows for a specific column 
print("Second column salaries:", salaries[:, 1]) 

# Step 4: Negative indexing 
print("Last year of experience:", years_exp[-1]) 

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [ 60  90 120 150]
Last year of experience: 10


In [8]:
import numpy as np

# Sample arrays
years_exp = np.array([1, 3, 5, 7, 10])
salaries = np.array([
    [40000, 45000, 50000],
    [50000, 55000, 60000],
    [60000, 65000, 70000]
])

# Step 1: Access individual element
print("First year of experience:", years_exp[0])

# Step 2: Slice arrays
print("First two salaries:", salaries[0, :2])  # First two elements of first row

# Step 3: Access all rows for a specific column
print("Second column salaries:", salaries[:, 1])

# Step 4: Negative indexing
print("Last year of experience:", years_exp[-1])

# Try It: Reverse arrays using slicing
reversed_years = years_exp[::-1]
print("Reversed years_exp:", reversed_years)

# Try It: Slice 2D arrays for subgroups of salaries
subgroup = salaries[0:2, 1:3]  # First two rows, columns 2 and 3
print("Subgroup of salaries:\n", subgroup)

First year of experience: 1
First two salaries: [40000 45000]
Second column salaries: [45000 55000 65000]
Last year of experience: 10
Reversed years_exp: [10  7  5  3  1]
Subgroup of salaries:
 [[45000 50000]
 [55000 60000]]


In [9]:
# Step 1: Reshape 1D array into 2x3 matrix for batch analysis 
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3)) 
print("Reshaped Experience Array:\n", reshaped_exp) 

# Step 2: Flatten 2D arrays back into 1D 
flattened_exp = reshaped_exp.flatten() 
print("Flattened Array:", flattened_exp) 

# Step 3: Transpose example 
print("Transposed Array:\n", reshaped_exp.T)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [10]:
import numpy as np

# Imagine we have 12 data points (like 12 samples of experience years)
data = np.arange(1, 13)
print("Original 1D data:", data)

# Reshape into 3x4 (3 samples, 4 features each)
reshaped_3x4 = data.reshape(3, 4)
print("Reshaped into 3x4:\n", reshaped_3x4)

# Reshape into 4x3 (4 samples, 3 features each)
reshaped_4x3 = data.reshape(4, 3)
print("Reshaped into 4x3:\n", reshaped_4x3)

# Reshape into 2x2x3 (like batches of 2, each with 2 rows and 3 features)
reshaped_2x2x3 = data.reshape(2, 2, 3)
print("Reshaped into 2x2x3:\n", reshaped_2x2x3)

Original 1D data: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped into 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped into 4x3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Reshaped into 2x2x3:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
# Step 1: Add a bonus array to salaries using broadcasting 
bonus = np.array([5, 10, 15]) 
salaries_with_bonus = salaries + bonus  # Adds corresponding bonus to each column 
print("Salaries after bonus:\n", salaries_with_bonus)

Salaries after bonus:
 [[40005 45010 50015]
 [50005 55010 60015]
 [60005 65010 70015]]


In [12]:
import numpy as np

# Sample salaries array
salaries = np.array([
    [40000, 45000, 50000],
    [50000, 55000, 60000],
    [60000, 65000, 70000]
])

# Scaling factor (e.g., 1.1 for a 10% increase)
scaling_factor = 1.1

# Broadcasting automatically applies the factor to every element
scaled_salaries = salaries * scaling_factor
print("Scaled Salaries:\n", scaled_salaries)

Scaled Salaries:
 [[44000. 49500. 55000.]
 [55000. 60500. 66000.]
 [66000. 71500. 77000.]]


In [13]:
# Step 1: Mean of years of experience 
print("Mean experience:", np.mean(years_exp))

# Step 2: Standard deviation of experience 
print("Std deviation of experience:", np.std(years_exp)) 

# Step 3: Max and Min salaries 
print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries)) 

# Step 4: Sum of salaries 
print("Sum of all salaries:", np.sum(salaries)) 

Mean experience: 5.2
Std deviation of experience: 3.1240998703626617
Max salary: 70000 Min salary: 40000
Sum of all salaries: 495000


In [14]:
import numpy as np

# Sample arrays
years_exp = np.array([1, 3, 5, 7, 10])
salaries = np.array([
    [40000, 45000, 50000],
    [50000, 55000, 60000],
    [60000, 65000, 70000]
])

# Median of years of experience
median_exp = np.median(years_exp)
print("Median experience:", median_exp)

# Median of salaries
median_salary = np.median(salaries)
print("Median salary:", median_salary)

# Percentiles of years of experience
percentile_25 = np.percentile(years_exp, 25)  # 25th percentile
percentile_75 = np.percentile(years_exp, 75)  # 75th percentile
print("25th percentile of experience:", percentile_25)
print("75th percentile of experience:", percentile_75)

# Percentiles of salaries
percentile_10_salary = np.percentile(salaries, 10)
percentile_90_salary = np.percentile(salaries, 90)
print("10th percentile of salaries:", percentile_10_salary)
print("90th percentile of salaries:", percentile_90_salary)

Median experience: 5.0
Median salary: 55000.0
25th percentile of experience: 3.0
75th percentile of experience: 7.0
10th percentile of salaries: 44000.0
90th percentile of salaries: 66000.0


In [15]:
# Step 1: Apply trigonometric functions 
angles = np.array([0, np.pi/4, np.pi/2]) 
print("Sine of angles:", np.sin(angles)) 
print("Cosine of angles:", np.cos(angles)) 

# Step 2: Apply function along rows (sum salaries per person) 
salary_sums = np.apply_along_axis(np.sum, 1, salaries) 
print("Sum of Salaries per person:", salary_sums) 

Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [135000 165000 195000]


In [16]:
import numpy as np

# Sample arrays
years_exp = np.array([1, 3, 5, 7, 10])
salaries = np.array([
    [40000, 45000, 50000],
    [50000, 55000, 60000],
    [60000, 65000, 70000]
])

# Try It: Apply sqrt and log transformations
sqrt_exp = np.sqrt(years_exp)
print("Square root of experience:", sqrt_exp)

log_exp = np.log(years_exp)
print("Log of experience:", log_exp)

# Try It: Apply custom function with np.apply_along_axis
# Example custom function: range (max - min) of each row
def row_range(row):
    return np.max(row) - np.min(row)

salary_ranges = np.apply_along_axis(row_range, 1, salaries)
print("Range of Salaries per person:", salary_ranges)

Square root of experience: [1.         1.73205081 2.23606798 2.64575131 3.16227766]
Log of experience: [0.         1.09861229 1.60943791 1.94591015 2.30258509]
Range of Salaries per person: [10000 10000 10000]


In [2]:
%pip install pandas

   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 851.1 kB/s eta 0:00:11
   -- ------------------------------------- 0.5/9.9 MB 851.1 kB/s eta 0:00:11
   --- ------------------------------------ 0.8/9.9 MB 831.3 kB/s eta 0:00:11
   --- ------------------------------------ 0.8/9.9 MB 831.3 kB/s eta 0:00:11
   ---- ----------------------------------- 1.0/9.9 MB 709.7 kB/s eta 0:00:13
   ---- ----------------------------------- 1.0/9.9 MB 709.7 kB/s eta 0:00:13
   ----- ---------------------------------- 1.3/9.9 MB 678.3 kB/s eta 0:00:13
   ------ --------------------------------- 1.6/9.9 MB 714.0 kB/s eta 0:00:12
   ------- --------------------


[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [18]:
import pandas as pd 

# Step 1: Create a NumPy array of random data 
data = np.random.randint(1, 50, size=(5, 3)) 

# Step 2: Convert the array into a DataFrame 
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z']) 
print("Generated Data:\n", df_data) 

# Step 3: Apply NumPy functions to DataFrame columns 
df_data['Log_X'] = np.log(df_data['X']) 
df_data['Sqrt_Y'] = np.sqrt(df_data['Y']) 
print("DataFrame with NumPy Transformations:\n", df_data) 

# Step 4: Analyze data using Pandas correlation 
print("Correlation Matrix:\n", df_data.corr())

Generated Data:
     X   Y   Z
0  18  23  10
1  32   8  34
2   6  34  11
3  17  46   1
4  19   6   7
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  18  23  10  2.890372  4.795832
1  32   8  34  3.465736  2.828427
2   6  34  11  1.791759  5.830952
3  17  46   1  2.833213  6.782330
4  19   6   7  2.944439  2.449490
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000 -0.607631  0.698781  0.956607 -0.632111
Y      -0.607631  1.000000 -0.594488 -0.546410  0.993022
Z       0.698781 -0.594488  1.000000  0.470009 -0.568738
Log_X   0.956607 -0.546410  0.470009  1.000000 -0.578256
Sqrt_Y -0.632111  0.993022 -0.568738 -0.578256  1.000000


In [19]:
import numpy as np
import pandas as pd

# Step 1: Create a NumPy array of random data
data = np.random.randint(1, 50, size=(5, 3))

# Step 2: Convert the array into a DataFrame
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data:\n", df_data)

# Try It: Compute overall column statistics
mean_X = np.mean(df_data['X'])
median_X = np.median(df_data['X'])
print("Mean of X:", mean_X)
print("Median of X:", median_X)

mean_Y = np.mean(df_data['Y'])
median_Y = np.median(df_data['Y'])
print("Mean of Y:", mean_Y)
print("Median of Y:", median_Y)

# Try It: Apply other NumPy functions
df_data['Square_Z'] = np.square(df_data['Z'])   # square transformation
df_data['Exp_X'] = np.exp(df_data['X'])         # exponential transformation
print("DataFrame with Additional Transformations:\n", df_data)

Generated Data:
     X   Y   Z
0  30  37   6
1  42   1  11
2  26  37  20
3  46   9  17
4   4   3  37
Mean of X: 29.6
Median of X: 30.0
Mean of Y: 17.4
Median of Y: 9.0
DataFrame with Additional Transformations:
     X   Y   Z  Square_Z         Exp_X
0  30  37   6        36  1.068647e+13
1  42   1  11       121  1.739275e+18
2  26  37  20       400  1.957296e+11
3  46   9  17       289  9.496119e+19
4   4   3  37      1369  5.459815e+01


In [20]:
# Step 1: Save the DataFrame to a CSV file 
df_data.to_csv('sample_data.csv', index=False) 
print("Data saved to 'sample_data.csv'.") 

# Step 2: Load the CSV file back into a new DataFrame 
df_imported = pd.read_csv('sample_data.csv') 
print("Imported DataFrame:\n", df_imported) 

# Step 3: Generate summary statistics 
summary_stats = df_imported.describe() 
print("Summary Statistics:\n", summary_stats) 

# Step 4: Display column means and standard deviations 
print("Column Means:\n", df_imported.mean()) 
print("Column Standard Deviations:\n", df_imported.std()) 

Data saved to 'sample_data.csv'.
Imported DataFrame:
     X   Y   Z  Square_Z         Exp_X
0  30  37   6        36  1.068647e+13
1  42   1  11       121  1.739275e+18
2  26  37  20       400  1.957296e+11
3  46   9  17       289  9.496119e+19
4   4   3  37      1369  5.459815e+01
Summary Statistics:
                X          Y          Z     Square_Z         Exp_X
count   5.000000   5.000000   5.000000     5.000000  5.000000e+00
mean   29.600000  17.400000  18.200000   443.000000  1.934010e+19
std    16.516658  18.132843  11.819475   536.743421  4.228019e+19
min     4.000000   1.000000   6.000000    36.000000  5.459815e+01
25%    26.000000   3.000000  11.000000   121.000000  1.957296e+11
50%    30.000000   9.000000  17.000000   289.000000  1.068647e+13
75%    42.000000  37.000000  20.000000   400.000000  1.739275e+18
max    46.000000  37.000000  37.000000  1369.000000  9.496119e+19
Column Means:
 X           2.960000e+01
Y           1.740000e+01
Z           1.820000e+01
Square_Z    4

In [21]:
import numpy as np
import pandas as pd

# Step 1: Create a NumPy array of random data
data = np.random.randint(1, 50, size=(5, 3))

# Step 2: Convert the array into a DataFrame
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Original Data:\n", df_data)

# Step 3: Add a new calculated column (Sum of X and Y)
df_data['Sum_XY'] = df_data['X'] + df_data['Y']
print("DataFrame with New Column:\n", df_data)

# Step 4: Save the modified DataFrame to a new CSV file
df_data.to_csv('modified_data.csv', index=False)
print("Modified DataFrame saved to 'modified_data.csv'.")

# Step 5: Load and review the new CSV file
df_imported = pd.read_csv('modified_data.csv')
print("Imported Modified DataFrame:\n", df_imported)

Original Data:
     X   Y   Z
0  18  36  13
1   5   9   1
2  44  48  43
3  31  27  15
4   5  12  14
DataFrame with New Column:
     X   Y   Z  Sum_XY
0  18  36  13      54
1   5   9   1      14
2  44  48  43      92
3  31  27  15      58
4   5  12  14      17
Modified DataFrame saved to 'modified_data.csv'.
Imported Modified DataFrame:
     X   Y   Z  Sum_XY
0  18  36  13      54
1   5   9   1      14
2  44  48  43      92
3  31  27  15      58
4   5  12  14      17


In [22]:
# Step 1: Load the Stack Overflow 2023 Developer Survey dataset 
df_kaggle = pd.read_csv('survey_results_public.csv') 
print("Loaded Dataset:\n", df_kaggle.head()) 

# Step 2: Select relevant columns 
df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedComp']] 
print("Subset of Data:\n", df_subset.head()) 

# Step 3: Clean the data by dropping rows with missing values 
df_clean = df_subset.dropna() 
print("Cleaned Data:\n", df_clean.head()) 

# Step 4: Categorize experience into groups 
df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 
'Junior') 

# Step 5: Group data by Country and ExperienceLevel, compute average salary 
grouped_data = df_clean.groupby(['Country', 
'ExperienceLevel'])['ConvertedComp'].mean() 
print("Grouped Average Salary:\n", grouped_data.head()) 

# Step 6: Reset index for readability 
grouped_data = grouped_data.reset_index() 
print("Formatted Grouped Data:\n", grouped_data.head())

FileNotFoundError: [Errno 2] No such file or directory: 'survey_results_public.csv'

In [3]:
%pip install survey_results_public.csv

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement survey_results_public.csv (from versions: none)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for survey_results_public.csv


In [6]:
import numpy as np
import pandas as pd

# Step 1: Load dataset (make sure the path is correct!)
df_kaggle = pd.read_csv("survey_results_public.csv")

# Step 2: Select relevant columns
df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedComp']]

# Step 3: Clean the data
df_clean = df_subset.dropna()

# Step 4: Categorize experience into groups
df_clean['YearsCodePro'] = pd.to_numeric(df_clean['YearsCodePro'], errors='coerce')
df_clean = df_clean.dropna(subset=['YearsCodePro'])
df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')

# Step 5a: Group by **EdLevel** instead of Country
grouped_edlevel = df_clean.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).reset_index()
print("Grouped by Education Level:\n", grouped_edlevel.head())

# Step 5b: Group by Country and compute median + std
grouped_country = df_clean.groupby('Country')['ConvertedComp'].agg(['mean','median','std']).reset_index()
print("Grouped by Country:\n", grouped_country.head())

# Step 6: Explore top 10 countries with highest average compensation
top10_countries = grouped_country.sort_values(by='mean', ascending=False).head(10)
print("Top 10 Countries by Average Compensation:\n", top10_countries)

FileNotFoundError: [Errno 2] No such file or directory: 'survey_results_public.csv'

In [7]:
import numpy as np 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294
 
np.random.seed(STUDENT_ID) 
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10) 
print(f"{STUDENT_NAME}'s Array:", data) 
 
mean_val = np.mean(data) 
std_val = np.std(data) 
print("Mean:", mean_val, "Std Dev:", std_val)

John Marco Donor's Array: [ 22 113 123  78  28  64  94  40 114 107]
Mean: 78.3 Std Dev: 35.94175844334831


In [8]:
import numpy as np 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294
 
np.random.seed(STUDENT_ID) 
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4)) 
print(f"{STUDENT_NAME}'s Matrix:\n", matrix) 
 
row_sums = np.sum(matrix, axis=1) 
col_sums = np.sum(matrix, axis=0) 
print("Row sums:", row_sums) 
print("Column sums:", col_sums) 

John Marco Donor's Matrix:
 [[27 22 14 39]
 [18 49 48 59]
 [24 14  2 28]]
Row sums: [102 174  68]
Column sums: [ 69  85  64 126]


In [5]:
import numpy as np 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294
 
np.random.seed(STUDENT_ID) 
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3)) 
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d) 
 
slice_mid = arr3d[:,1,:] 
print("Slice[:,1,:]:\n", slice_mid)

John Marco Donor's 3D Array:
 [[[21 13  6]
  [17 16 15]
  [23 13  1]]

 [[ 8  7 22]
  [17 10  3]
  [23 13  8]]

 [[ 6 15 14]
  [21  7  0]
  [21  4 20]]]
Slice[:,1,:]:
 [[17 16 15]
 [17 10  3]
 [21  7  0]]


In [ ]:
import numpy as np 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294
 
np.random.seed(STUDENT_ID) 
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10) 
filtered = x[(x>STUDENT_ID%50) & (x<STUDENT_ID%100)] 
print(f"{STUDENT_NAME}'s Original:", x) 
print("Filtered subset:", filtered)

John Marco Donor's Original: [ 22 113 123  78  28  64  94  40 114 107]
Filtered subset: [78 64]


In [10]:
import numpy as np 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294
 
np.random.seed(STUDENT_ID) 
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2)) 
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2)) 
print("Matrix A:\n", A) 
print("Matrix B:\n", B) 
 
product = A @ B 
det_A = np.linalg.det(A) 
print("A @ B:\n", product) 
print("Determinant of A:", det_A)

Matrix A:
 [[27 22]
 [14 39]]
Matrix B:
 [[18 49]
 [48 59]]
A @ B:
 [[1542 2621]
 [2124 2987]]
Determinant of A: 745.0000000000001


In [11]:
import numpy as np 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294
 
angles = np.linspace(0, 2*np.pi, 8) 
sine_vals = np.sin(angles) 
cos_vals = np.cos(angles) 
print(f"{STUDENT_NAME}'s Angles:", angles) 
print("Sine:", sine_vals) 
print("Cosine:", cos_vals)

John Marco Donor's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [13]:
import numpy as np 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294
 
np.random.seed(STUDENT_ID) 
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4)) 
arr[::2, ::2] = 0 
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr) 

John Marco Donor's Modified 4x4 Array:
 [[ 0 22  0 39]
 [18 49 48 59]
 [ 0 14  0 28]
 [30 41 40 55]]


In [14]:
import numpy as np 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294
 
np.random.seed(STUDENT_ID) 
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10) 
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail') 
print(f"{STUDENT_NAME}'s Scores:", scores) 
print("Grades:", grades) 

John Marco Donor's Scores: [ 21 112 122  77  27  63  93  39 113 106]
Grades: ['Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass']


In [15]:
import numpy as np 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294
 
np.random.seed(STUDENT_ID) 
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4)) 
flat_arr = arr.flatten() 
transposed_arr = arr.T 
print("Original array:\n", arr) 
print("Flattened:", flat_arr) 
print("Transposed:\n", transposed_arr)

Original array:
 [[27 22 14 39]
 [18 49 48 59]
 [24 14  2 28]]
Flattened: [27 22 14 39 18 49 48 59 24 14  2 28]
Transposed:
 [[27 18 24]
 [22 49 14]
 [14 48  2]
 [39 59 28]]


In [16]:
import numpy as np 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294
 
np.random.seed(STUDENT_ID) 
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3)) 
mask = arr % 2 == 0 
arr[mask] = -1 
print("Array with conditional replacements:\n", arr) 

Array with conditional replacements:
 [[27 -1 -1]
 [39 -1 49]
 [-1 59 -1]]


In [17]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294
 
np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'Name': [STUDENT_NAME]*5, 
    'Score': np.random.randint(STUDENT_ID%50, 
STUDENT_ID%100+50,5), 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5) 
}) 
print(df)

               Name  Score  YearsCodePro
0  John Marco Donor    134            16
1  John Marco Donor     65            15
2  John Marco Donor    121            23
3  John Marco Donor     82            13
4  John Marco Donor     61             1


In [18]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294
 
np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'], 
    # Corrected to use a functional salary range, e.g., 40000 to 150000 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean() 

In [19]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294 
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'Country': ['Philippines','USA','UK','Canada','Germany'], 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
 
top5 = df.sort_values(by='ConvertedComp', ascending=False) 
print(top5) 

       Country  ConvertedComp
3       Canada         111825
0  Philippines         104277
4      Germany          87216
2           UK          66022
1          USA          43021


In [20]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294
 
np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'Name':[STUDENT_NAME]*5, 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5) 
}) 
high_exp = df[df['YearsCodePro']>STUDENT_ID%10] 
print(high_exp)

               Name  YearsCodePro
0  John Marco Donor            21
1  John Marco Donor            13
2  John Marco Donor             6
3  John Marco Donor            17
4  John Marco Donor            16


In [26]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 
150000, 5)}) 
 
bins = [0, 50000, 100000, 150000, 200000] 
labels = ['0-50k', '50-100k', '100-150k', '>150k'] 
 
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels) 
print(df)

   ConvertedComp   Bracket
0         104277  100-150k
1          43021     0-50k
2          66022   50-100k
3         111825  100-150k
4          87216   50-100k


In [21]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294
 
np.random.seed(STUDENT_ID) 
 
# Original Code Issue:  
# np.random.randint(STUDENT_ID%40000, STUDENT_ID%150000, 5)  
# -> np.random.randint(12345, 12345, 5) which is a zero-length range. 
 
# Corrected Code: Using a functional salary range (40000 to 150000) 
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 
150000, 5)}) 
 
df['LogComp'] = np.log(df['ConvertedComp']) 
print(df)

   ConvertedComp    LogComp
0         104277  11.554806
1          43021  10.669444
2          66022  11.097743
3         111825  11.624690
4          87216  11.376143


In [22]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294
 
np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5), 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
 
corr_matrix = df.corr() 
print(corr_matrix) 

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000       0.697486
ConvertedComp      0.697486       1.000000


In [23]:
import numpy as np
import pandas as pd

STUDENT_NAME = "John Marco Donor"
STUDENT_ID = 294
np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'EdLevel':['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# FIX: Keep the assignment and the groupby logic on the same line (or use parentheses)
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean', 'median', 'std']).reset_index()

print(summary)

    EdLevel      mean    median           std
0  Bachelor  108051.0  108051.0   5337.241984
1    Master   65118.5   65118.5  31250.584195
2       PhD   66022.0   66022.0           NaN


In [24]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "John Marco Donor" 
STUDENT_ID = 294
 
np.random.seed(STUDENT_ID) 
 
# Generate salaries: [100727, 136195, 130612, 100727, 95233] 
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 
150000, 5)}) 
 
threshold = 110000 
 
# Create the 'HighPay' column using np.where() 
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No') 
 
print(df)

   ConvertedComp HighPay
0         104277      No
1          43021      No
2          66022      No
3         111825     Yes
4          87216      No


In [25]:
import numpy as np
import pandas as pd

STUDENT_NAME = "John Marco Donor"
STUDENT_ID = 294
np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# FIX: Move the code up to this line
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean', 'max'])

print(top_countries)

                 mean     max
Country                      
Canada       111825.0  111825
Germany       87216.0   87216
Philippines  104277.0  104277
UK            66022.0   66022
USA           43021.0   43021
